### ISSUE TITLE
problemi con harvesting al riavvio

### ISSUE THREAD

**Issue by piersoft** [italia/dati-ckan-docker#5]
ciao a tutti. dopo aver installato l'immagine in un docker sul mio mac, aver settato un harvesting andato a buon fine da varie source (sia con catalog.rdf che direttamente sulla url del ckan remoto), ho riavviato la VM con il docker e l'istanza ckan non sale più:

```
2017-10-01 19:18:07,605 DEBUG [ckanext.harvest.queue] pika connection using {'retry_delay': 2.0, 'frame_max': 10000, 'channel_max': 0, 'locale': 'en_US', 'socket_timeout': 0.25, 'ssl': False, 'host': 'localhost', 'ssl_options': {}, 'virtual_host': '/', 'heartbeat': 0, 'credentials': <pika.credentials.PlainCredentials object at 0x7fdff8256110>, 'backpressure_detection': False, 'port': 5672, 'connection_attempts': 1}
2017-10-01T19:18:07.619042789Z 
2017-10-01 19:18:07,614 ERROR [pika.adapters.base_connection] socket error: Connection refused
2017-10-01 19:18:07,615 WARNI [pika.adapters.base_connection] Could not connect due to "Connection refused," retrying in 2 sec
2017-10-01 19:18:07,615 ERROR [pika.adapters.base_connection] Could not connect: Connection refused
Traceback (most recent call last):
  File "/usr/local/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 189, in command
    consumer = get_fetch_consumer()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 468, in get_fetch_consumer
    consumer = get_consumer(get_fetch_queue_name(), fetch_routing_key)
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 250, in get_consumer
    connection = get_connection()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 38, in get_connection
    return get_connection_amqp()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 61, in get_connection_amqp
    return pika.BlockingConnection(parameters)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 61, in __init__
    super(BaseConnection, self).__init__(parameters, on_open_callback)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 513, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 804, in _connect
    self._adapter_connect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 138, in _adapter_connect
    super(BlockingConnection, self)._adapter_connect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 120, in _adapter_connect
    self.params.retry_delay)
pika.exceptions.AMQPConnectionError: 2.0
Traceback (most recent call last):
  File "/usr/local/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/local/lib/python2.7/dist-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/serve.py", line 329, in loadapp
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 48, in make_app
    **app_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/pylons_app.py", line 113, in make_pylons_stack
    who_parser.parse(open(app_conf['who.config_file']))
IOError: [Errno 2] No such file or directory: '/etc/ckan/default/who.ini'
```

ho provato più volte, poi mi sono arreso. suggerimenti?

aggiornamento: ho chiuso l'interfaccia grafica kitematic, ho spento la VM, riavviata e poi da riga di comando rilanciato il `docker-compose up -d`  e ora sta reggendo. Ma temo che se riapro l'interfaccia grafica o riavvio, il problema potrebbe sussistere. a voi

**Comment by fabiofumarola** [comment]
Ciao Piersoft,
mi sembra che questo errore sia legato all'ordine di startup dei servizi. Sembra che il web harvester cerchi di collegarsi a Redis ma questo servizio non e' ancora attivo. Per fare un test veloce prova a riavviare tutto con docker compose e poi riavviare solo ckan.

```
# restart di tutti i servizi
$ docker-compose up -d

# qui dovresti avere un errore per il container ckan

$ docker-compose restart ckan

```

Se questo e' vero abbiamo trovato il problema.
Fammi sapere che in questo caso vediamo come fare una patch.

**Comment by piersoft** [comment]
credo che @fabiofumarola abbia ragione. dopo il docker-compose bisogna aspettare 20-30 secondo e poi finire con l'init.sh . poi è tutto ok
